### ISSUE TITLE
[BUG] Missing instructions and sphinx package for building docs

### ISSUE THREAD

**Issue by lbk003** [KhalisFoundation/banidb-api-python#45]
**Describe the bug**
No instructions on how to build the docs
sphinx package is missing from requirements.txt file.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Python Version: [e.g. 3.8]
 - OS: [e.g. Ubuntu 18.02]

**Additional context**

**Comment by MySmilingTurban** [comment]
Waheguru ji ka Khalsa, Waheguru ji ki Fateh ji
@lbk003 do you want me to add the instructions as a readme or as a part of [rtfd.io](rtfd.io/banidbpy) ??

**Comment by lbk003** [comment]
How about a section in the readme in building docs?

**Comment by MySmilingTurban** [comment]
sure, will do it right away

**Comment by MySmilingTurban** [comment]
also, sphinx package isn't needed in the requirements.txt as it is not essential for the package itself
sphinx is basically just for devs (those who are changing the docs)

**Comment by MySmilingTurban** [comment]
fixed
